.versionrc
Makefile
README.md
deploy/olm/kustomization.yaml
deploy/operator/kustomization.yaml

This commit adds a script which runs after the version is bumped. The
script sets the operator image tag to match the one specified in the
VERSION file.

chore: update operator version after initiating a release

---

.github/e2e-tests/action.yaml
test/e2e/main_test.go

During the e2e run, the operators run in the default namespace. This
makes it harder to do a cleanup after the test is finished. It also does
not test cases when operators are installed in the non-default namespace
which is a more realistic scenarion.
This commit changes the operators' namespace to 'operators'.

test: run operators in dedicated namespace

---

pkg/controllers/prometheus-operator/controller.go
pkg/eventsource/ticker.go

This commit extracts the ticker event source into a dedicated package so
that it can be used for multiple controllers.

refactor: move ticker to eventsource package

---

pkg/controllers/grafana-operator/controller.go
test/e2e/grafana_operator_test.go

MSO maintains an OLM OperatorGroup and Subscription through which it
installs a Grafana Operator.
This commit adds a test to ensure that these resources are created.
It also adds assertions that the resources are restored if someone
deletes them.

test: add additional grafana-operator tests

---

hack/kind/audit-policy.yaml
hack/kind/config.yaml

This commit enables kube-apiserver audit logs in a local KinD cluster
for easier debugging and troubleshooting.

chore: enable audit logs in local kind cluster

---

.github/e2e-tests-olm/action.yaml
hack/kind/config.yaml
hack/kind/registry.yaml

This commit exposes the local docker registry on NodePort 30000 and
removes the need to use port-forward from the host.

chore: remove the need for port-forwarding to the local registry

---

pkg/controllers/monitoring-stack/components.go

DeepCopyObject() was used to avoid modifying the object in informer's
cache but this isn't the case as `client.Get(ctx, gvk, &obj)` ensures
that a new/empty object is passed which then gets initialised by the
cache-reader.
See also: https://github.com/kubernetes-sigs/controller-runtime/blob/1638a6a9b82dc1e0046c7a1006f12dacd9475f54/pkg/cache/internal/cache_reader.go#L81

perf: avoid calling deepcopy of existing object

---

deploy/operator/monitoring-stack-operator-cluster-role.yaml
pkg/controllers/grafana-operator/controller.go
pkg/eventsource/ticker.go
test/e2e/grafana_operator_test.go

This commit deploys a default Grafana instance in the
monitoring-stack-operator namespace. The instance is configured to
collect all dashboards with the label: `app.kubernetes.io/part-of: monitoring-stack-operator`.

feat: deploy a default grafana instance

---

.github/workflows/release.yaml

The release flow still uses go 1.15 which causes our release-related
scripts to break.
This commit changes the go version to 1.17 everywhere in the CI.

ci: fix release flow

---

deploy/operator/monitoring-stack-operator-cluster-role.yaml
pkg/controllers/grafana-operator/controller.go

This commit adjusts the grafana-operator controller permissions and
removes `get` permissions for all the resources which the controller
needs to watch.

perf: fine-tune grafana-operator permissions

---

.github/e2e-tests-olm/action.yaml
.github/env
.github/olm-publish/action.yaml
.github/workflows/olm-candidate.yaml
.github/workflows/olm-stable.yaml
.github/workflows/pr-checks.yaml
.github/workflows/release.yaml

This commit extracts the go version in a central place and imports it
into the environment from the required CI jobs.

ci: extract go version in a central place

---

.github/e2e-tests-olm/action.yaml
.github/go-cache/action.yaml
.github/olm-publish/action.yaml

This commit enables caching of go modules in order to speed up building
and testing the operator image. The cache load strategy tries to
load the latest cache from the current branch, then falls back to the
latest main cache from the branch and finally falls back to the latest cache
from any branch.

ci: cache go dependencies when running e2e tests

---

Makefile
deploy/operator/monitoring-stack-operator-cluster-role.yaml
pkg/controllers/monitoring-stack/alertmanager.go
pkg/controllers/monitoring-stack/components.go
pkg/controllers/monitoring-stack/controller.go
test/e2e/framework/assertions.go
test/e2e/monitoring_stack_controller_test.go

This commit adds an Alertmanager to each MonitoringStack and
configures the Prometheus instances to send alerts to that Alertmanager
instance.

feat: Deploy an Alertmanager instance for each stack

---

.golangci.yml
pkg/controllers/monitoring-stack/alertmanager.go
pkg/controllers/monitoring-stack/components.go
test/e2e/framework/assertions.go
test/e2e/framework/framework.go
test/e2e/monitoring_stack_controller_test.go

The prometheus-operated service is a statefulset governing service. It
is intended to be used by the statefulset controller for assigning a
network identity to individual pods, and is not supposed to be used for
http communication.
This commit creates a dedicated service for each Prometheus statefulset
and reconfigures the GrafanaDataSource to query it instead.

feat: query Prometheus through a dedicated service

---

pkg/controllers/grafana-operator/controller.go
pkg/controllers/monitoring-stack/alertmanager.go
pkg/controllers/monitoring-stack/components.go
test/e2e/grafana_operator_test.go
test/e2e/main_test.go
test/e2e/monitoring_stack_controller_test.go
test/e2e/prometheus_operator_test.go

Replaces all hard-coded APIVersion: "group/version" with
`package.SchemeGroupVersion.String()` to prevent any typos and to use the
computed value.

fix: use api-version from scheme information

---

.github/e2e-tests-olm/action.yaml
Makefile
hack/kind/config.yaml
hack/kind/operator-metrics-service.yaml
pkg/controllers/grafana-operator/controller.go
pkg/controllers/monitoring-stack/controller.go
test/e2e/framework/assertions.go
test/e2e/grafana_operator_test.go
test/e2e/monitoring_stack_controller_test.go
test/e2e/prometheus_operator_test.go

This patch makes use of promq tool to scape operator metrics to ensure
that it does not generate any reconcile errors.

ci: ensure operator has no reconcile errors

---

.github/e2e-tests-olm/action.yaml
Makefile
test/e2e/framework/framework.go
test/e2e/main_test.go
test/e2e/monitoring_stack_controller_test.go

Flaky tests can be hard to troubleshoot in the CI. This commit adds a
step in the pipeline which captures the cluster-state after each e2e
test run. It also adds a --retain-namespace flag which is toggled in the
pipeline to prevent deletion of the e2e-tests namespace.

ci: capture cluster state after e2e run

---

.github/e2e-tests-olm/action.yaml
.github/olm-publish/action.yaml
.github/tools
.github/tools-cache/action.yaml
.github/workflows/pr-checks.yaml
Makefile

Previously, we have seen that downloading of tools like `oc` can fail due to 
transient errors. These tools are downloaded for every CI run and do not change
often. 
This PR reduces the need to download these tools over and over by making use
of  github's cache to cache all the tools downloaded by `make tools`. The cache
relies on the checksum of `.github/tools` file as key, so  any change to the 
`.github/tools` file will result in a new set of tools being downloaded.

ci: cache development tools

---

deploy/operator/monitoring-stack-operator-cluster-role.yaml
hack/grafana-dashboard.yaml
pkg/controllers/grafana-operator/controller.go

The Grafana Operator is a third party bundle and its releases are not in
our control. The 4.0.2 release was buggy and should not have been used at all.
This commit makes sure that new versions are not installed
automatically.

fix: prevent automatic upgrades of Grafana Operator

---

.github/e2e-tests-olm/action.yaml
hack/kind/config.yaml
pkg/controllers/monitoring-stack/alertmanager.go
test/e2e/monitoring_stack_controller_test.go

This commit ensures that Alertmanager instances are deployed on
different nodes. It also reduces the number of instances to 2 to make
sure we don't have unnecessary resource usage.

feat: deploy alertmanagers on different nodes

---

README.md

kubectl apply error out when crds have large annotations as in prometheus crd
`The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`
This issue is there after upgrading prometheus to 0.52.1. We can either overcome it by `kubectl create` or by adding flag `--server-side` in `kubectl apply`, I am updating to create for simplicity
Signed-off-by: Jayapriya Pai <janantha@redhat.com>

docs: change to kubectl create for creating crds

---

deploy/operator/monitoring-stack-operator-cluster-role.yaml
pkg/controllers/monitoring-stack/alertmanager.go
pkg/controllers/monitoring-stack/components.go
pkg/controllers/monitoring-stack/controller.go
test/e2e/framework/framework.go
test/e2e/monitoring_stack_controller_test.go

This commit adds a Pod Disruption Budget for the Alertmanagers backing
single monitoring stack. The commit also adds a test to make sure all
alertmanagers cannot be evicted at once.

feat: add a pod disruption budget for Alertmanager

---

Makefile
pkg/controllers/grafana-operator/controller.go
pkg/controllers/grafana-operator/filters.go

This commit upgrades the Grafana Operator to 4.1.0 and configures the
operator to scan dashboards from all namespace. This change was
introduced in 4.0.2 [1].
https://github.com/grafana-operator/grafana-operator/pull/579

feat: upgrade grafana-operator to 4.1.0

---

pkg/controllers/grafana-operator/controller.go
pkg/controllers/monitoring-stack/controller.go

The operator currently outputs messages even for operatons which are
no-op. This makes it hard to understand what the operator is doing.
This commit increases the log-level for operations which do not change
the cluster state, and only outputs a log message when a change is
actually made.

refactor: reduce logging verbosity

---

deploy/operator/monitoring-stack-operator-rules.yaml

This is a small change to update the label and name for monitoring-stack-operator rule file

fix: correct the naming for mso rule file

---

deploy/operator/monitoring-stack-operator-cluster-role.yaml
pkg/controllers/grafana-operator/controller.go

We currently start an informer on Grafana CRs as soon as the operator
starts. This is problematic during installations because the Grafana CRD
will only become available once the grafana operator is installed. As a
result, we quite often get flakes in the CI related to deletion and
restoring of Grafana related resources.
This commit modifies the behavior of the Grafana Operator controller to
establish a watch only when the CRDs have been installed in the cluster.
It also creates watches on all Grafana related resources in order to resolve 
the flakes happening in the CI.

fix: establish a watch on Grafana CRs ince the CRD is present

---

deploy/operator/monitoring-stack-operator-cluster-role.yaml
pkg/controllers/grafana-operator/controller.go

Previously grafana-operator used `source.Kind` to watch the
resources which was far less efficient than the singleResourceInformer.
This patch makes use of `source.NewKindWithCache` which allows building
a cache/informers that watches only the `monitoring-stack-operator`
namespace and only those resources that has the label
`app.kubernetes.io/managed-by=monitoring-stack-operator`
NOTE: `msoClient` is created to make use of the cache.

fix: optimise watches used in grafana operator

---

Makefile
README.md
hack/kind/config.yaml

k8s v1.21 image has issues with OLM installation. See https://github.com/orgs/rhobs/teams/monitoring-stack-operator-maintainers/discussions/1
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>

chore: Recommend to use k8s v1.22 image for kind cluster

---

pkg/controllers/monitoring-stack/components.go
pkg/controllers/monitoring-stack/controller.go
test/e2e/framework/assertions.go
test/e2e/monitoring_stack_controller_test.go

this fix will clean up the grafana data source created by the monitoring
stack on deleting the monitoring stack

fix: cleaning up grafana datasource on deleting monitoring stack

---

.github/tools
.github/tools-cache/action.yaml
Makefile
Makefile.tools
docs/api.md

Here is how the docs generated by this tool look like: https://github.com/fpetkovski/monitoring-stack-operator/blob/crd-docs/docs/api.md
The only downside of the tool is that it's not able to link to external resources because it relies to yaml files instead of go structs.
We can look into an alternative solution if this one's too verbose.

docs: auto generate CRD docs

---

deploy/operator/monitoring-stack-operator-cluster-role.yaml
hack/kind/config.yaml
pkg/apis/v1alpha1/types.go
pkg/controllers/monitoring-stack/controller.go
pkg/controllers/thanos-querier/components.go
pkg/controllers/thanos-querier/controller.go
test/e2e/framework/assertions.go
test/e2e/thanos_querier_controller_test.go

This commit refactors the Thanos Querier controller to remove unused
code and simplify the reconciliation logic.

Clean up thanos controller

---

.github/workflows/pr-checks.yaml
Makefile
Makefile.tools

Without this we potentially run local checks and ghub action check
with two different versions.

ci: use Makefile for golangci-lint check

---

README.md
hack/kind/config.yaml

Closes #128
There are certain things that you cannot test on a single node. There are also parts of the application that do not work on a single node (The AlertManager StatefulSet with PodAntiAffinity) 
see #128 for more details.
This feature request is to give the use an alternative kind cluster configuration with the same low barrier to entry. (just copy and paste)
This setup gives the user 3 nodes, for a more production feel than a single node.
```
k get no 
NAME                 STATUS   ROLES                  AGE   VERSION
kind-control-plane   Ready    control-plane,master   50s   v1.22.4
kind-worker          Ready    <none>                 15s   v1.22.4
kind-worker2         Ready    <none>                 15s   v1.22.4
```
The end to end tests **do not break** when you run 3 nodes on …

chore: 3 node kind cluster with comments addressed

---

.github/olm-publish/action.yaml
Makefile
Makefile.tools

Previously, catalog images only used to have :latest image tags. Since
Quay images without tags get garbage collected, it wasn't possible to
pin down a catalog image by its sha256.
This PR, creates a catalog image which has the same version as the
bundle and the operator image. Additionally, it also tags this
versioned image as `latest` so that it is possible to make continuous
deployments (useful for development channel) should the users choose it.
Fixes: https://issues.redhat.com/browse/MON-2498

ci: publish versioned catalog images

---

cmd/operator/main.go

Format log timestamp in the RFC3339. The motivation here is to have human readable time format.
E.g.  The log timestamp is  `1.6523301588633049e+09` is now formatted as `2022-05-13T13:23:10Z`

style: switch to human readable time format in logs

---

deploy/operator/monitoring-stack-operator-cluster-role.yaml
pkg/controllers/monitoring-stack/alertmanager.go
pkg/controllers/monitoring-stack/components.go
pkg/controllers/monitoring-stack/controller.go
test/e2e/monitoring_stack_controller_test.go

Server side apply has been in beta since kubernetes 1.16 and stable
since 1.22. It greatly reduces client complexity, since no
get-patch-update cycles are needed anymore.
Additionally server side apply allows for controllers to handle user
changes on managed resources much more easily, if that need arises in
the future.
This also adds a `GenerationChangedPredicate` to the GrafanaDataSource watch.

refactor: use server side apply in mso controller

---

README.md

fix: change slack details in README according to rename

---

deploy/dependencies/kustomization.yaml
deploy/operator/observability-operator-cluster-role.yaml
deploy/operator/observability-operator-deployment.yaml
pkg/controllers/monitoring/monitoring-stack/alertmanager.go
pkg/controllers/monitoring/monitoring-stack/components.go
pkg/controllers/monitoring/monitoring-stack/controller.go

When running in namespace with Pod Security Standard profile "restricted"
we need to set RunAsNonRoot and SeccompProfile to all workloads running
on that namespace. Futhermore on OpenShift to run with a SeccompProfile
set we need to grant service accounts premisisons to use the SCC
nonroot-v2 
Fixes https://github.com/rhobs/observability-operator/issues/149

fix: Set seccomp profiles and grant SAs necessary premissions to run

---

.github/e2e-tests-olm/action.yaml
deploy/olm/kustomization.yaml

Additionally set the node-role.kubernetes.io/infra label on the master
node in our e2e test kind cluster.

feat: set soft affinity on operator deployment

---

deploy/dependencies/kustomization.yaml
deploy/operator/observability-operator-cluster-role.yaml
pkg/controllers/monitoring/monitoring-stack/alertmanager.go
pkg/controllers/monitoring/monitoring-stack/components.go
pkg/controllers/monitoring/monitoring-stack/controller.go

Necessary for cases where nonroot-v2 still does not exist e.g OpenShift 4.10. Otherwise prometheus-operator pods would not be able to start

fix: grants SA of components access to nonroot SCC

---

deploy/dependencies/kustomization.yaml
deploy/operator/observability-operator-deployment.yaml
pkg/controllers/monitoring/monitoring-stack/alertmanager.go
pkg/controllers/monitoring/monitoring-stack/components.go

It seems that built-in SCCs (except `privileged`) don't allow to set the
seccomp profile [1]. Until this is fixed in OpenShift, we should leave
it to the default (which is already `RuntimeDefault`).
[1] https://github.com/openshift/cluster-kube-apiserver-operator/issues/1325
Fixes #163

fix: remove SeccompProfile

---

.github/e2e-tests-olm/action.yaml

This patch adds a workaround for the OLM registry bug
Fixes: #170

ci: fix failing e2e test

---

deploy/dependencies/kustomization.yaml
deploy/operator/kustomization.yaml
docs/assess-resources.md
hack/loadtest/test.sh

Problem: we pull the Prometheus Operator (p-o) deployment from
the upstream repo as a dependency. However this manifest sets
a very low limit to the p-o resources, this limit is easily hit
when the operator is managing multiple Prometheus instances.
Solution: remove current limits and load testing on OO and p-o
and observe the resources they consume. Establish a baseline for
both and then multiply that baseline by 3 and give some headroom
Issue https://issues.redhat.com/browse/MON-2648
Closes https://github.com/rhobs/observability-operator/issues/166

fix: updates resources for OO and p-o

---

.github/e2e-tests-olm/action.yaml
Makefile

This updates the Makefile to use Podman as the default container runtime.
If Podman is not available then fallback to docker.

chore: use Podman as the default container runtime

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
cmd/operator/main.go
deploy/operator/observability-operator-deployment.yaml
pkg/operator/operator.go

This adds basic health probe endpoint (using the controller-runtime
options) and exposes the port via the existing OBO service

feat: add health probe

---

pkg/apis/monitoring/v1alpha1/types.go
pkg/controllers/monitoring/monitoring-stack/conditions.go
pkg/controllers/monitoring/monitoring-stack/conditions_test.go

The convention is to report only true,false or unknown as the condition status value.

fix: do not report Available=degraded condition

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
deploy/olm/bases/observability-operator.clusterserviceversion.yaml

This commit hides prometheus, alertmanager, thanosruler from
OLM UI.
Jira: https://issues.redhat.com/browse/MON-2835

fix: hide internal CRDs from OLM UI

---

pkg/controllers/monitoring/monitoring-stack/conditions.go
pkg/controllers/monitoring/monitoring-stack/conditions_test.go
pkg/controllers/monitoring/monitoring-stack/controller.go

generation difference
This adds check comparing the Prometheus observedGeneration to the current MonitoringStack generation. If there is a difference then the MonitoringStack status is not updated.

fix: do not update MonitoringStack status in case of Prometheus

---

.github/e2e-tests-olm/action.yaml
.github/go-cache/action.yaml
.github/olm-publish/action.yaml
.github/tools-cache/action.yaml
.github/workflows/olm-candidate.yaml
.github/workflows/olm-stable.yaml
.github/workflows/pr-checks.yaml
.github/workflows/release.yaml

GitHub release workflow was broken by changes made in commit 4625e3e which was intended to fix deprecation message but the usage was wrong and didn't correctly fix all warnings. This commit aims to fix all warnings and deprecation messages.

fix: broken release workflow

---

Makefile

To enable continuous delivery of OBO to OSD/ROSA clusters via app-interface, the OLM catalog image must be tagged with a git short hash that represents the commit that was used for the creation of the catalog.
This patch adds a make target `catalog-tag-sha` that tags the catalog image with the SHA of the commit that CI bot makes when it updates the catalog.
In addition to that the PR also update the Makefile to reflect the FBC change that was pushed to olm-catalog branch but was missing in main.
JIRA: https://issues.redhat.com/browse/MON-2859

build: publish catalog image with SHA

---

bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
docs/api.md
pkg/apis/monitoring/v1alpha1/types.go
test/e2e/monitoring_stack_controller_test.go

This updates the valid log level values in the API. This adds new "error" log level and changes the "warning" log level to "warn".

fix: update log levels to reflect alertmanager levels

---

bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
docs/api.md
pkg/apis/monitoring/v1alpha1/types.go
test/e2e/monitoring_stack_controller_test.go

This updates my original PR cbb95f32509ecde346b70eb30bd558483f162e2f to allow 0 number of replicas for the Prometheus config.

fix: number of Prometheus replicas can be 0

---

Makefile

Using git as the fetch protocol requires ghub auth to be setup. If I want to run the release process in a container, I need to add my auth key to the containers. For fetching tags that is really not needed.

refactor: use https to fetch tags in release targets

---

hack/kind/setup.sh

Previously, when running hack/kind/setup.sh, the script ran its validations such as if the tools are installed, local-registry is entry is added to /etc/hosts etc in the middle of the run instead of the start. This required the cluster to be deleted again and again until all validations pass.
This commit improve the experience
* running validations in the starting of the script
* ensuring binaries in <project-root>/tmp/bin takes precedence all the time (as opposed to only when kubeclt was missing)
* Better emojis 🔔 ✅ 🛑
```
❯ ./hack/kind/setup.sh
🔆🔆🔆  Validating Prerequisites  🔆🔆🔆
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🛑 operator-sdk not found - did you run 'make tools'?
🛑 /etc/hosts does not contain local-registry entry
🔔 No …
```

chore: improve kind setup UX

---

.github/package-operator-publish/action.yaml
.github/workflows/package-operator-stable.yaml
.github/workflows/release.yaml
Makefile
deploy/package-operator/dependencies-kubeconfig/kustomization.yaml
deploy/package-operator/dependencies-kubeconfig/patches/kubeconfig-volume.yml
deploy/package-operator/operator-kubeconfig/kustomization.yaml
deploy/package-operator/operator-kubeconfig/patches/kubeconfig-volume.yml

This adds github actions to generate and publish the package image to quay.
Versioning and publishing policy follows what we do for the OLM artifacts with one difference:
Since package-operator does not have a notion of channels, this currently only pushes packages for development versions (with the `$tag-$date` tagging scheme and for releases (i.e. not for prereleases).
If we want packages for pre-releases, we need to discuss an addition to the tagging policy.
https://issues.redhat.com/browse/MON-2892

build: generate and publish package in ghub actions

---

.github/olm-publish/action.yaml
.github/workflows/release.yaml

Problem: In the make target `catalog-tag-sha` we want to use main's sha sum to tag the catalog image. The olm-publish action however adds commits to the local main branch before that happens, resulting in a sha tag that doesn't correspond to main.
Solution: The olm-publish action creates a branch to add commits in.

build: create branch for olm-publish action

---

bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
docs/api.md
pkg/apis/monitoring/v1alpha1/types.go
pkg/controllers/monitoring/monitoring-stack/components.go
pkg/controllers/monitoring/monitoring-stack/conditions.go
pkg/controllers/monitoring/monitoring-stack/conditions_test.go
pkg/controllers/monitoring/monitoring-stack/controller.go
test/e2e/monitoring_stack_controller_test.go

feat: add resourceDiscovery status condition
The ResourceSelector field in a MonitoringStack CR can be set to nil.
This is passed on to the Prometheus CR and can be used to disable all
service discovery and thus most scraping (we add prometheus and
alertmanager scrape jobs via additionalScrapeConfigs).
When this is configured we now set a new status condition to alert users
to the fact that no service discovery is configured.
Fixes: https://issues.redhat.com/browse/MON-2864

feat: add resourceDiscovery status condition

---

.github/workflows/release.yaml

Fixes: https://github.com/rhobs/observability-operator/issues/214

ci: move from actions/create-release to ncipollo/release-action

---

.github/tools
.github/workflows/pr-checks.yaml
Makefile
Makefile.tools
hack/kind/setup.sh

This add a `shellcheck` make target and PR test. Additionall this fixes existing shellcheck issues.
Fixes: https://github.com/rhobs/observability-operator/issues/212

build: add make lint-shell and add to PR checks

---

.github/workflows/olm-candidate.yaml
.github/workflows/olm-stable.yaml
.github/workflows/release.yaml
Makefile

Problem: In bc3b0d202f0ea36c04a20fbcd44a51d2504d2aed the git rev-parse command was changed to tag catalog images with the `main` commit on which this catalog image is build. The argument to rev-parse was changed from `HEAD` to `main`. In some workflows however `main` might not be a valid local revision.
To reporduce:
```
cd $(mktemp -d)
git init observability-operator
git remote add origin https://github.com/rhobs/observability-operator
cd observability-operator
git remote add origin https://github.com/rhobs/observability-operator
git fetch --prune origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
git checkout --force refs/tags/v0.0.18
git rev-parse main
```
Solution: Add a new Makefile variable `RELEASH_SHA`. If its not defined we use `origin/main`, which should provide …

build: add option to pass SHA to tag catalog

---

bundle/manifests/observability-operator-rules_monitoring.coreos.com_v1_prometheusrule.yaml
deploy/monitoring/observability-operator-rules.yaml
pkg/apis/monitoring/v1alpha1/register.go

This updates alert names to follow the camel format convention for alert rules.

fix: rename alert names to follow convention

---

test/run-e2e.sh

This should help with our increasing frequent e2e test failures due to timeout of the go test command.
~Additionally this adds a refactor in the test code.~

Extend e2e test timeout

---

bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
docs/api.md
pkg/apis/monitoring/v1alpha1/types.go

The MonitoringStack CRD uses megabytes for default resource limits and requests. Everywhere else we use mebibytes.
This commit changes the default to mebibytes as well. Fixes: https://issues.redhat.com/browse/MON-2865

fix: use mebibytes instead of megabytes for resource defaults

---

Makefile
test/Dockerfile
test/osd-e2e.sh

Package tests to execution in OSD pipelines. 
See: https://github.com/openshift/osde2e-example-test-harness
Related issue: https://issues.redhat.com/browse/MON-3125

ci: package osd e2e tests

---

test/run-e2e-ocp.sh
test/run-e2e.sh

Previously, the cleanup of ocp test will be run twice; i.e.
1. One after the tests are run
2. When the script exits
Additionally both test scripts failed to return the actual test run return code and only returned 1 on failure. This patch fixes both issues.

fix: e2e test cleanup and exit code

---

docs/user-guides/server-side-apply.md

Adds examples for
- adding/updating a field managed by MonitoringStack
- adding/updating a field not managed by MonitoringStack
fixes: MON-3147, MON-3148, #245

docs: add server-side apply examples for updating Prometheus object

---

go.mod
go.sum
pkg/operator/operator.go
test/e2e/monitoring_stack_controller_test.go

Update this test case when a new Prometheus field is managed by Observability Operator.

test(managedFields): added test case to assert Obo managed fields of Prometheus object

---

test/osd-e2e.sh

osde2e test harness requires that the junit xml report follows junit-<report>.xml

fix(test): ensure test report follows osde2e recommendation

---

docs/developer.md
pkg/controllers/monitoring/monitoring-stack/components.go
test/e2e/monitoring_stack_controller_test.go

feat: ObO sets the `probeSelector` and `probeNamespaceSelector` fields in the Prometheus `.spec`
feat: ObO sets the `scrapeConfigSelector` and `scrapeConfigNamespaceSelector` fields in the Prometheus `.spec`
fixes: #283

feat: add probe and scrapeConfig selectors

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
deploy/dependencies/kustomization.yaml

NOTE: this HACK removes the RuntimeDefault seccomProfile from prometheus-operator deployments (opearator and webhook) so that the bundle installs fine on all OpenShift versions >= 4.9.
Without this HACK pods fail to be created with the following status error ...
```
status:
conditions:
message: '
pods "obo-prometheus-operator-5864dd8b49-xjs55" is forbidden:
unable to validate against any security context constraint: [pod.metadata.annotations.seccomp.security.alpha.kubernetes.io/pod:
Forbidden: seccomp may not be set pod.metadata.annotations.container.seccomp.security.alpha.kubernetes.io/prometheus-operator:
Forbidden: seccomp may not be set provider "anyuid":
Forbidden: not usable by user or serviceaccount pod.metadata.annotations.seccomp.security.alpha.kubernetes.io/pod:
Forbidden: …
```

fix: ensure OLM bundle installs fine all supported OpenShift Versions

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
deploy/olm/bases/observability-operator.clusterserviceversion.yaml

This is an optional but recommended detail for the bundle to be published to 
OpenShift Community Catalog. 
See: https://redhat-openshift-ecosystem.github.io/community-operators-prod/packaging-required-fields/

fix: add repo details to bundle

---

deploy/olm/syncselector-template.yaml
hack/olm/catalog-src.yaml
hack/olm/k8s/catalog-src.yaml

* Restricted SCC enforcement will be added with OCP 4.14
* Updating the catalogsource to allow the operator to get deployed
* Clusters that don't support the setting (<4.12) will ignore it
Jira: OSD-15621

Make catalogsource compatible with restricted SCC enforcement

---

deploy/olm/syncselector-template.yaml

This commit specifies .spec.grpcPodConfig.nodeSelector and .spec.grpdPodConfig.tolerations to schedule this operator's registry pod to infra nodes when possible.
[OSD-6629](https://issues.redhat.com//browse/OSD-6629)

fix: enforce scheduling registry pod onto infra nodes

---

test/e2e/monitoring_stack_controller_test.go

Fix issue #311 
Prometheus pod need more resources and has complicated configuration, replace it with prometheus example app pod

fix: test case multi-namespace_support

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
deploy/olm/kustomization.yaml

While the observability-operator, obo-prometheus-operator and obo-prometheus-operator-admission-webhook deployments are configured to be scheduled preferably on infra nodes, they lacked the required toleration that would enable them being scheduled properly.
This change fixes the issue by adding the expected toleration.
https://issues.redhat.com/browse/MON-3299

fix: add node tolerations to deployments

---

test/e2e/framework/assertions.go
test/e2e/monitoring_stack_controller_test.go
test/e2e/po_admission_webhook_test.go
test/e2e/prometheus_operator_test.go
test/e2e/thanos_querier_controller_test.go

- Clean up deprecated funcs
- Minor clean ups

fix: Clean up deprecated functions 

---

.github/e2e-tests-olm/action.yaml

GitHub workflow is giving off a warning about the node version used for
some of the actions (engineerd/setup-kind) being deprecated. This commit
changes the plugin to helm/kind-action to avoid that.
Signed-off-by: Daniel Mellado <dmellado@redhat.com>

fix: update github workflow to use node>=16

---

README.md
test/run-e2e-ocp.sh

fix: test scripts and readme doc about uninstallation

---

test/e2e/monitoring_stack_controller_test.go

This PR makes it so DefaultTimeout is used accordingly among the
different tests and assertions.
Signed-off-by: Daniel Mellado <dmellado@redhat.com>

fix: use framework default timeout in ns tests

---

OWNERS
OWNERS_ALIASES
cmd/OWNERS
docs/OWNERS
jsonnet/OWNERS
pkg/OWNERS
test/OWNERS

The OWNERS files are very simple and need to only be placed in the right locations. Actual membership is managed through OWNERS_ALIASES. Currently this reflects the github groups `observability-operator-contributors` `observability-operator-maintainers`.
The current setup allows reviews and approvals by contributors to code, but requires maintainer review for changes to build artifacts.

chore: add OWNERS files

---

.github/osd-test-harness-publish/action.yaml
.github/workflows/release.yaml

MON-3355: build: build and publish test harness images in release workflow

---

.github/e2e-tests-olm/action.yaml
.github/env
.github/olm-publish/action.yaml
.github/osd-test-harness-publish/action.yaml
.github/package-operator-publish/action.yaml
.github/workflows/pr-checks.yaml
.github/workflows/release.yaml

ci: use go version in go.mod file

---

.gitignore
bundle.Dockerfile

Submit then bundle.Dockerfile.
Checked several operator repositories, they contain the docker file, such as
https://github.com/openshift/open-telemetry-opentelemetry-operator

ci: bundle dockerfile is needed for prow job

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
deploy/olm/bases/observability-operator.clusterserviceversion.yaml

Add description field to CSV base of every owned CRD to generate correct description when run bundle generate.

fix: add description field to CSV base

---

test/Dockerfile

sigs.k8s.io/controller-runtime@0.16.3 requires go1.20.

ci: bump test/Dockerfile go image base

---

build/Dockerfile
test/Dockerfile

This change adds the `-tags netgo,osusergo` argument to Go commands to get fully-static binaries.

chore: build static Go binaries

---

docs/developer.md

This commit reorganizes the `docs/developer.md` page by separating the content into 3 main sections:
* Development setup
* Contribution guidelines
* Release management

chore: update developer documentation

---

bundle/manifests/monitoring.rhobs_alertmanagerconfigs.yaml
bundle/manifests/monitoring.rhobs_alertmanagers.yaml
bundle/manifests/monitoring.rhobs_podmonitors.yaml
bundle/manifests/monitoring.rhobs_probes.yaml
bundle/manifests/monitoring.rhobs_prometheusagents.yaml
bundle/manifests/monitoring.rhobs_prometheuses.yaml
bundle/manifests/monitoring.rhobs_prometheusrules.yaml
bundle/manifests/monitoring.rhobs_scrapeconfigs.yaml
bundle/manifests/monitoring.rhobs_servicemonitors.yaml
bundle/manifests/monitoring.rhobs_thanosrulers.yaml
bundle/manifests/obo-prometheus-operator-admission-webhook_policy_v1_poddisruptionbudget.yaml
bundle/manifests/obo-prometheus-operator-admission-webhook_v1_service.yaml
bundle/manifests/obo-prometheus-operator_v1_service.yaml
bundle/manifests/observability-operator.clusterserviceversion.yaml
cmd/operator/main.go
deploy/dependencies/kustomization.yaml
deploy/operator/kustomization.yaml
test/e2e/monitoring_stack_controller_test.go

We missed updating to the new prometheus-operator version in the bundle. Additionally this sets the new `--images` cli args for the operator deployment.

fix: update versions in bundle generation

---

test/e2e/framework/monitoring_stack.go
test/e2e/monitoring_stack_controller_test.go

Stabilize case: TestMonitoringStackController/single_prometheus_replica_has_no_pdb
fix error "the object has been modified; please apply your changes to the latest version and try again: failed to update monitoring stack" tracked by https://issues.redhat.com/browse/COO-42

test: stabilize case single_prometheus_replica_has_no_pdb

---

.github/tools
Makefile.tools
olm/observability-operator-index/index.yaml

These were removed in 1875b9e99d14b7a84b59d0ab23ae939da27e6061 and are needed for release automation via olm/update-channels.sh.
Fixes: https://issues.redhat.com/browse/COO-17

fix: add channel marker back into index file

---

.github/e2e-tests-olm/action.yaml
pkg/controllers/monitoring/thanos-querier/components.go
test/e2e/framework/assertions.go
test/e2e/framework/framework.go
test/e2e/monitoring_stack_controller_test.go
test/e2e/thanos_querier_controller_test.go
test/run-e2e.sh

Before thanos was only listening on localhost. Relying on the default setting allows user to modify that via server side apply and add a proxy chain.
Fixes: https://issues.redhat.com/browse/COO-14

fix: use thanos default port in service and containerPort

---

test/e2e/framework/assertions.go
test/e2e/thanos_querier_controller_test.go

This should fix the test failing with:
```
E0322 09:17:13.829822   42915 portforward.go:409] an error occurred forwarding 10902 -> 10902: error forwarding port 10902 to pod b607bb8a7641f1f305367d46323a9525283056d28cb3d86ac85cc8d0b5bc59e5, uid : sandbox b607bb8a7641f1f305367d46323a9525283056d28cb3d86ac85cc8d0b5bc59e5 is not running
panic: lost connection to pod
```

test:thanos querier e2e test - wait for deployment to be ready

---

test/e2e/monitoring_stack_controller_test.go

I suspect that the test was flaky because it uses the address of the loop variable (see https://go.dev/blog/loopvar-preview).

chore: fix assertAlertmanagersAreResilientToDisruption()

---

bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
bundle/manifests/observability-operator.clusterserviceversion.yaml
deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
docs/api.md
pkg/apis/monitoring/v1alpha1/types.go
pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
pkg/controllers/monitoring/monitoring-stack/components.go
test/e2e/monitoring_stack_controller_test.go

This PR adds an option to enable a featuregate on prometheus to accept data on the otlp/http ingestion path.
Is that something we can a here or should it be an option to accept multiple featuregates?
TODO:
cc @simonpasquier

apis: provide option to enable otlp/http receiver

---

pkg/controllers/monitoring/monitoring-stack/alertmanager.go
pkg/reconciler/reconciler.go

Cluster roles aren't namespace-scoped and can't have namespace-scoped owner references.
Closes [COO-117](https://issues.redhat.com//browse/COO-117)

COO-117: fix: remove invalid owner ref on cluster role

---

test/e2e/framework/assertions.go
test/e2e/main_test.go

Follow-up of #460 to prevent any regression.

COO-117: test: add test to detect OwnerRefInvalidNamespace event

---

test/e2e/framework/assertions.go
test/e2e/monitoring_stack_controller_test.go

This should fix test failure [COO-79](https://issues.redhat.com/browse/COO-79)
`monitoring_stack_controller_test.go:585: assertion failed: 0 (prom.Status.Replicas int32) != 1 (int32)`
Also fix
[COO-84](https://issues.redhat.com/browse/COO-84) [QE] Case Alertmanager_runs_in_HA_mode is not stable
`monitoring_stack_controller_test.go:99: statefulsets.apps "alertmanager-alerting" not found`

test: prometheus scale down e2e test

---

test/e2e/monitoring_stack_controller_test.go

stabilize test case Controller_reverts_back_changes_to_Prometheus
[COO-101](https://issues.redhat.com/browse/COO-101)

test: stablize Controller_reverts_back_changes_to_Prometheus

---

test/e2e/monitoring_stack_controller_test.go

fix issue https://issues.redhat.com/browse/COO-158

fix: duplicate monitoringstack name caused case unstable

---

Makefile

Three changes, but all in the Makefile:
- Fix git command to ignore external diff tools
- Fix definition of default target
- Add a target for unit tests (optional, but I like being able to run tests with a simple command)
I can split this up into separate PRs, if you like.

fix: default goal in makefile and add goal for unit tests

---

pkg/apis/uiplugin/v1alpha1/types.go
pkg/controllers/uiplugin/compatibility_matrix.go
pkg/controllers/uiplugin/compatibility_matrix_test.go
pkg/controllers/uiplugin/components.go

These commits have been extracted from #477, so that they can be separately reviewed and merged quicker.
PTAL @jgbernalp

fix: Some typos and reconciliation of optional UIPlugin components

---

pkg/controllers/uiplugin/compatibility_matrix.go
pkg/controllers/uiplugin/compatibility_matrix_test.go

This PR fixes the min version semver validation for allowing plugins to be enabled in nightly cluster versions.
[COO-179](https://issues.redhat.com//browse/COO-179)

 COO-179: fix: compatibility matrix version validation

---

pkg/controllers/uiplugin/components.go

use correct port for korrel8r deployment so the service binds correctly

COO-180: fix: bind service with correct container port for korrel8r

---

pkg/controllers/uiplugin/controller.go

This PR adjusts the merge object so only console plugins are changed in the console resource to avoid affecting other fields.

COO-181: fix: Change only the console plugins to avoid mutating existing cluster configuration

---

pkg/controllers/uiplugin/troubleshooting_panel.go

Although the troubleshooting panel will deploy after #501, it reconciles in a loop.
Since the UIPlugin proxy spec is still of type v1alpha1, when it is created it gets converted to use v1 instead. Having `authorize: false` creates a v1 version that is different enough from from the v1alpha1 to cause a reconciliation. However, the conversion again happens leading to a loop.

COO-183: Prevent Reconcile Loop for Troubleshooting Panel UIPlugin

---

OWNERS_ALIASES

Given that Observability Operator is growing in terms of componentes,
once the initial bootstrap has been done, and before we properly split
this into different owners files I'm adding some folks to take care of
specific dashboards and korrel8r parts.
Signed-off-by: Daniel Mellado <dmellado@redhat.com>

chore: edit OWNERS maintainers

---

pkg/controllers/uiplugin/distributed_tracing.go

Updates are needed to reflect the changes in PR: https://github.com/openshift/distributed-tracing-console-plugin/pull/15, which allows the distributed-tracing-console-plugin to use this proxy service  at the endpoint : `/api/proxy/plugin/distributed-tracing-console-plugin/backend`

fix: update distributed_tracing.go to include a service proxy

---

Makefile.tools

Action publish-olm-candidate https://github.com/rhobs/observability-operator/actions/runs/9462114451/job/26065129373 is failing due an error in shellheck curl.

fix: shellcheck wrong curl

---

pkg/controllers/uiplugin/components.go
pkg/controllers/uiplugin/logging.go

This PR adds the korrel8r proxy configuration so the the logging view plugin can discover korrel8r and correlation links are shown.

COO-186: fix: add korrel8r proxy configuration to logging view plugin

---

.github/e2e-tests-olm/action.yaml
.github/olm-publish/action.yaml
.github/osd-test-harness-publish/action.yaml
.github/package-operator-publish/action.yaml
.github/tools-cache/action.yaml
.github/workflows/pr-checks.yaml
.github/workflows/release.yaml

This change updates all actions to use actions/setup-go@v5. In this version, caching is enabled by default hence it removes all `cache: true` occurrences.

chore: update GitHub actions to setup-go@v5

---

bundle/manifests/observability.openshift.io_uiplugins.yaml
deploy/crds/common/observability.openshift.io_uiplugins.yaml
pkg/apis/uiplugin/v1alpha1/types.go

[OU-402](https://issues.redhat.com/browse/OU-402)
[COO-164](https://issues.redhat.com/browse/COO-164)
This PR adds a pattern restriction for the UIPlugin name so only a single instance of a specific plugin is allowed

feat: restrict UIPlugin CRD names to allow a single instance per type

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
cmd/operator/main.go
deploy/operator/observability-operator-cluster-role.yaml
pkg/controllers/uiplugin/controller.go
pkg/controllers/uiplugin/troubleshooting_panel.go

This PR creates the required clusterroles and clusterrolebindingss, so that korrel8r can query all the required resources
Adds additional clusterrolebinding and rolebinding so that korrel8r can connect to Prometheus endpoints and retrieve relevant data. 
All of the roles and rolebindings are created within the operator

Add Clusterrole to allow Korrel8r to view all signal data

---

pkg/controllers/uiplugin/components.go
pkg/controllers/uiplugin/components_test.go
pkg/controllers/uiplugin/controller.go
pkg/controllers/uiplugin/distributed_tracing.go
pkg/controllers/uiplugin/logging.go
pkg/controllers/uiplugin/plugin_info_builder.go
pkg/controllers/uiplugin/troubleshooting_panel.go
pkg/operator/scheme.go

This PR adds support for ConsolePlugin CR v1 for OCP 4.17. For older versions the v1alpha1 support was kept

COO-225: fix: Add support for ConsolePlugin v1

---

bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
bundle/manifests/observability-operator.clusterserviceversion.yaml
deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
docs/api.md
pkg/apis/monitoring/v1alpha1/types.go
pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
pkg/controllers/monitoring/monitoring-stack/alertmanager.go
pkg/controllers/monitoring/monitoring-stack/components.go

Add support for tolerations and nodeselectors in the monitoringstack CRD.

COO-261: Support tolerations and nodeselector in Monitoringstack

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
deploy/operator/observability-operator-cluster-role.yaml
pkg/controllers/uiplugin/controller.go
pkg/controllers/uiplugin/distributed_tracing.go

Update RBAC to include listing TempoMonolithic CRs.
Soon the Distributed Tracing UI Plugin will support Tempo deployments in monolithic mode (TempoMonolithic CR).
https://issues.redhat.com/browse/OU-490
cc @jgbernalp

feat: update RBAC to include listing TempoMonolithic CRs

---

docs/user-guides/observability-ui-plugins.md

This PR addresses [OU-486](https://issues.redhat.com/browse/OU-486), [OU-468](https://issues.redhat.com/browse/OU-468), and [OU-469](https://issues.redhat.com/browse/OU-469).
It add compatibility matrixes for the obo version, OCP version, and plugin availability, as well as for the obo version, the OCP version, and the feature set used. It also adds information on the logging-view plugin and gives more detail on the usage patterns of these plugins.

docs: UIPlugin updates

---

docs/user-guides/observability-ui-plugins.md

When following the original docs, I was getting:
```
Danger alert:An error occurred
Error "Invalid value: "object": UIPlugin name must be
'distributed-tracing' if type is DistributedTracing" for field "<nil>".
```

docs: fix UI docs

---

docs/user-guides/observability-ui-plugins.md

Since we validate the name of UIPlugins to ensure only one is deployed, the example in the docs should reflect the correct name to allow for users to copy it

docs: fix dashboard plugin name in example

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
deploy/olm/bases/observability-operator.clusterserviceversion.yaml
deploy/package-operator/dependencies/kustomization.yaml

This is aligned with the other CRDs like Prometheus and Alertmanager.

chore: flag PrometheusAgent CRD as internal

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
deploy/olm/bases/observability-operator.clusterserviceversion.yaml

The page isn't really up-to-date. Also removed sthaha from the list of maintainers.

COO-356: remove link to rhobs-handbook.netlify.app

---

pkg/controllers/uiplugin/compatibility_matrix_test.go
pkg/controllers/uiplugin/controller.go
pkg/controllers/uiplugin/distributed_tracing.go
pkg/controllers/uiplugin/logging.go
pkg/controllers/uiplugin/plugin_info_builder.go
pkg/controllers/uiplugin/troubleshooting_panel.go

This PR 
- Extracts the plugin console names into a map, so the console name can be obtained from the plugin type
- Adds a finalizer to the UIPlugin so it can be removed from console resource when the plugin is deleted, it uses the console name from the map to do so

COO-152: fix: Add finalizer to cleanup the console after UIPlugin is deleted

---

pkg/controllers/uiplugin/plugin_info_builder.go

This PR uses the plugin names the console expect so the routing for resources and proxies works correclty

COO-451: fix: use expected plugin console names

---

pkg/controllers/uiplugin/compatibility_matrix.go
pkg/controllers/uiplugin/controller.go
pkg/controllers/uiplugin/plugin_info_builder.go

This PR looks to address [COO-318](https://issues.redhat.com/browse/COO-318) by adding support level annotations to the UIPlugins based on their type after they are created.
This adds an extra couple of reconciliations for each plugin, but doesn't trigger a reconciliation loop and is able to stabilize.

COO-318: add uiplugin support annotations when created

---

build/Dockerfile
must-gather/README.md
must-gather/collection-scripts/common.sh
must-gather/collection-scripts/gather

Fixes: [COO-498](https://issues.redhat.com//browse/COO-498)

feat: add basic gather script for monitoring components

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
deploy/operator/observability-operator-cluster-role.yaml
go.mod
go.sum
pkg/controllers/operator/components.go
pkg/controllers/operator/controller.go
pkg/operator/operator.go

Fixes: [COO-482](https://issues.redhat.com//browse/COO-482)

feat: add operator controller to add ServiceMonitor

---

OWNERS_ALIASES

Add myself and @zhuje to the contributors list. Once [COO-242](https://www.google.com/url?q=https://issues.redhat.com/browse/COO-242) has been finalized we can be moved down to a lower directory level if desired.

chore: add observability ui team members to contributors

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
deploy/olm/bases/observability-operator.clusterserviceversion.yaml

This change adds the 'operatorframework.io/cluster-monitoring=true' annotation to the operator's CSV.

COO-483: feat: add "Enable cluster monitoring" checkbox to OCP console

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
deploy/olm/bases/observability-operator.clusterserviceversion.yaml

Fixes: [COO-32](https://issues.redhat.com//browse/COO-32)

chore: add suggested namespace to bundle

---

test/run-e2e-ocp.sh

enable platform monitoring
fix issue [COO-618](https://issues.redhat.com/browse/COO-618)

fix: failed to get metric when install upstream ObO on OCP

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
deploy/operator/observability-operator-cluster-role.yaml
go.mod
go.sum
pkg/controllers/uiplugin/compatibility_matrix_test.go
pkg/controllers/uiplugin/controller.go
pkg/controllers/uiplugin/monitoring.go
pkg/controllers/uiplugin/monitoring_test.go
pkg/controllers/uiplugin/plugin_info_builder.go
pkg/operator/scheme.go

This PR looks to remove the ACM version check and remove the dependency of this repository on github.com/stolostron/multiclusterhub-operator. This change allows for a user to create a UIPlugin, with type monitoring and the feature acm enabled before having ACM installed.
While this could lead to some wasted resources as the monitoring-console-plugin deployment is created without showing any UI changes, it makes the installation process of the plugin and ACM reversible and more seamless. When ACM is then installed, the Observe > Alerting section will already be available for use.
Further discussion in [slack](https://redhat-internal.slack.com/archives/C03FR4B5MS7/p1740047197384099).

NO-JIRA: remove acm-version check for acm-alerting ui feature

---

docs/user-guides/observability-ui-plugins.md

PR https://github.com/rhobs/observability-operator/pull/664, the monitoring UIPlugin custom resource definition has changed. This PR updates the docs to reflect those changes.

NO-JIRA: update docs with new monitoring UIPlugin schema

---

pkg/controllers/uiplugin/compatibility_matrix.go
pkg/controllers/uiplugin/compatibility_matrix_test.go

[[COO1.1] - OCP4.15 - ui-logging-pf4 (v6.0) is deployed instead of ui-logging (v6.1)](https://issues.redhat.com/browse/COO-749)
[[COO1.1] - OCP4.15 - ui-distributed-tracing-pf4 (v0.3) is deployed instead of ui-distributed-tracing (v0.4)](https://issues.redhat.com/browse/COO-748)
Fix compatibility matrix to catch the edge case where clusterVersion is `v4.15.0-0.nightly`. 
The compatibility_matrix is returning the incorrect image when clusterVersion v4.15.0-0.nightly. It should be returning with imageKey `ui-logging` and `ui-distributed-tracing` when clusterVersion v4.15.0-0.nightly. 
Normalizing/standardizing the string format allows semver to compare lexically compare v4.15.0-0.nightly > v4.15.0-0. This allows the compatibility matrix to return `ImageKey: "ui-logging"`.  
**Before** …

 COO-749 and COO-748: Fix compatibility_matrix so OCP v4.15.0-0.nightly deploys logging and distributed-tracing image containing PF5

---

deploy/olm/syncselector-template.yaml

This PR removes OBO subscription from Hypershift service clusters (SCs)
The following MR install COO on those clusters:
https://gitlab.cee.redhat.com/service/osd-fleet-manager/-/merge_requests/1043
This MR must be merged after above PR

OSD-28131: Deploying COO in place of OBO on SC clusters

---

deploy/olm/syncselector-template.yaml

Follow up of this PR: https://github.com/rhobs/observability-operator/pull/667
It was actually a bad idea to deploy COO through `osd-fleet-manager` as discussed [there](https://github.com/rhobs/observability-operator/pull/667#discussion_r2007813490).
Indeed `osd-fleet-manager` come too late in the install process of (Hypershift) SC clusters.
Typically ACM will be installed before COO is installed... but ACM needs to deploy OBO/COO specific service monitor which is only possible if COO is installed before ACM.

feat: deploying COO in place of OBO on SC clusters

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
bundle/manifests/observability.openshift.io_uiplugins.yaml
deploy/crds/common/observability.openshift.io_uiplugins.yaml
docs/api.md
pkg/apis/uiplugin/v1alpha1/types.go
pkg/controllers/uiplugin/logging.go

Fixes: https://issues.redhat.com/browse/COO-818
Adds a schema field to the logging view plugin to add support for OTEL labels
Requires https://github.com/openshift/logging-view-plugin/pull/277 from the plugin side

COO-818: feat: add schema configuration for logging view plugin

---

docs/user-guides/observability-ui-plugins.md

Add missing `schema` field for the ui logging plugin example

docs: add schema field for ui logging

---

.github/olm-publish/action.yaml

The issue leads that no new bundle and catalog image generated and pushed to quay after PR merged
Such as 
https://github.com/rhobs/observability-operator/actions/runs/14902238105/job/41857694406

fix: github action failure to set up do in olm publish

---

.github/olm-publish/action.yaml

Further fix of https://github.com/rhobs/observability-operator/pull/723
[COO-936](https://issues.redhat.com/browse/COO-936)

fix: further fix github action olm publish failure

---

pkg/controllers/uiplugin/controller.go
pkg/controllers/uiplugin/logging.go
pkg/controllers/uiplugin/plugin_info_builder.go

Use a default name to allow to create the logging plugin even if no loki stacks can be discovered in the cluster.

COO-760: fix: allow to create a logging plugin without a loki stack

---

pkg/controllers/uiplugin/accelerators.go
pkg/controllers/uiplugin/components.go
pkg/controllers/uiplugin/controller.go
pkg/controllers/uiplugin/monitoring.go
pkg/operator/scheme.go

Common accelerator perses dashboard contains metrics that are common for different accelerators' vendors. The dashboard will be deployed along with UI plugin

 COO-942: Adding deployment of common accelerator perses dashboard

---

cmd/operator/main.go
pkg/controllers/uiplugin/compatibility_matrix.go
pkg/controllers/uiplugin/compatibility_matrix_test.go

[monitoring-console-plugin-0.4](https://github.com/openshift/monitoring-plugin/tree/release-coo-0.4) patternfly v5, Bug fixes
[monitoring-console-plugin-0.5](https://github.com/openshift/monitoring-plugin/tree/release-coo-0.5) patternfly v6, react-router v5, incident bug fixes
https://issues.redhat.com/browse/OU-585
konflux-release-data (VPN required): https://gitlab.cee.redhat.com/releng/konflux-release-data/-/merge_requests/6422
konflux-coo: https://github.com/rhobs/konflux-coo/pull/1135
1. Update main.go to include the two monitoring-console-plugin stream (v0.4.0 and v0.5.0) 
2. Update compatibility-matrix.go to assign the  image name `monitoring-plugin-pf5` when OCP version 4.15 - 4.18, and image `monitoring-plugin` when OCP version 4.19+ is detected (this image contains patternfly …

feat: add monitoring-plugin stream 0.4 and 0.5

---

cmd/operator/main.go

In preparation for COO 1.2 release, update the troubleshooting plugin to reference a new image which contains the lastest commits from https://github.com/openshift/troubleshooting-panel-console-plugin/tree/release-0.4
Quay (tag v0.4.1)
https://quay.io/repository/openshift-observability-ui/troubleshooting-panel-console-plugin?tab=tags
JIRA
https://issues.redhat.com/browse/OU-585

chore: update troubleshooting plugin image tag

---

bundle/manifests/observability-operator.clusterserviceversion.yaml
deploy/perses/perses-operator-cluster-role.yaml
deploy/perses/perses-operator-deployment.yaml
pkg/controllers/uiplugin/monitoring.go

Update the perses operator to the newest version, add secret retrieval to permission set of perses operator, and pass in the secret name and paths to retrieve the cert

feat: update perses operator to v0.1.12

---

bundle/manifests/perses.dev_perses.yaml
deploy/perses/crds/perses.dev_perses.yaml
go.mod
go.sum

This PR fixes a change which added some required fields to the perses CRD, without incrementing the version, which caused the operator upgrade to fail.

COO-1046: revert changes to required fields within the CRD

---

build/Dockerfile
go.mod
go.sum
pkg/apis/monitoring/v1alpha1/register.go
pkg/apis/observability/v1alpha1/register.go
pkg/apis/uiplugin/v1alpha1/register.go
test/Dockerfile

This removes the `replace` command and the temporary workarounds for the new API module dependency. Maybe it would be good to add something like:
```
go mod edit -require "github.com/rhobs/observability-operator/pkg/apis@v$(VERSION)"
```
but not sure where (perhaps the `make initiate-release` target?) and maybe it's too early (since there's no tag for the API module)

fix: remove replace command after introducing API module

---

Makefile

Changes were initially made on the olm-catalog branch.

build: fix catalog-image target

---

.github/workflows/pr-checks.yaml

The `commitlint.config.mjs` seems to have stopped working, so just skip the step on dependabot PRs.

ci: don't run commitlint on dependabot PRs

---

pkg/controllers/uiplugin/components.go
pkg/controllers/uiplugin/controller.go

This PR:
- fixes the empty response when reading the cluster.console.operator.openshift.io, this is caused from reading from the cache when using the k8sClient. As the cluster plugins is read occasionally we can use the apiReader to get latest results.
- Fixes the names of some role bindings so labels are valid

COO-1248: fix: use apiReader for correct ui plugin registration

---

bundle/manifests/perses.dev_perses.yaml
deploy/perses/crds/perses.dev_perses.yaml

There was a misalignment between the Perses CRD in this repository with the Perses CRD from the operator at `quay.io/openshift-observability-ui/perses-operator:v0.2-go-1.23`.
I ran `make bundle` in `github.com/rhobs/perses-operator`, `v0.2.0-golang_1_23` branch and copy&pasted the updated CRD.
cc @PeterYurkovich @jgbernalp 
Resolves: https://issues.redhat.com/browse/COO-1197

fix: sync Perses CRD with perses-operator

---

pkg/controllers/monitoring/thanos-querier/controller.go

This commit updates ThanosQuerier controller's logs to report the number of MonitoringStacks being evaluated and the number being selected eventually.

chore: update log message

---

test/e2e/observability_installer_test.go
test/e2e/traces_telemetrygen.yaml
test/e2e/traces_tempo_readiness.yaml

This PR adds a job that checks the tempo readiness probe before ingesting data.

COO-1252: chore: fix flaky ObservabilityInstaller tests
