rhobs/observability-operator

- CHANGELOG.md
> chore(release): 0.0.3

- .github/workflows/pr-checks.yaml
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>
> chore: add linter to validate github actions yaml

- cmd/operator/main.go
- go.mod
- pkg/controllers/grafana-operator/controller.go
- pkg/controllers/monitoring-stack/alertmanager.go
- pkg/controllers/monitoring-stack/components.go
- pkg/controllers/monitoring-stack/controller.go
- pkg/operator/operator.go
- pkg/operator/scheme.go
- test/e2e/grafana_operator_test.go
- test/e2e/main_test.go
- test/e2e/monitoring_stack_controller_test.go
- test/e2e/prometheus_operator_test.go
This commit changes the module name so that it can be fetched with the
go get command.
> feat: make the module go-gettable

- pkg/controllers/monitoring-stack/components.go
- test/e2e/monitoring_stack_controller_test.go
The prometheus instances are incorrectly configured for self-scraping
and scrape themselves twice, once through the prometheus job and once
more through the alertmanager job. The reason for this is because they
were using the app.kubernetes.io/part-of label instead of the
app.kubernetes.io/name label to identify their own service.
> fix: fix self-scrape prometheus configuration for stacks

- pkg/controllers/grafana-operator/controller.go
Previously, install-plan for the desired version of Grafana Operator was
obtained by lookup the status.installPlanRef of the subscription. This
isn't reliable since the installPlanRef can point to a version higher
than desired and the reconcile loop would wait for ever without
installing Grafana.
E.g. say we wanted to install `4.0.1` and the installPlanRef refers to
`4.0.2` because by the time reconcile loop was trigger, OLM already
updated the installPlanRef to the next upgradable version - 4.0.2, the
grafana controller would wait for ever to install the operator.
This is fixed by following the steps below.
1. Iterate  all install-plans in the monitoring-stack-operator namespace
2. Filter the plan that matches the desired CSV version
3. Wait for the plan to be properly initialised (i.e. …
> fix: install-plan approval logic to approve the right plan

- deploy/operator/kustomization.yaml
- deploy/operator/monitoring-stack-operator-rules.yaml
- deploy/operator/monitoring-stack-operator-service-monitor.yaml
- deploy/operator/monitoring-stack-operator-service.yaml
This commit adds initial rule file for monitoring-stack-operator
Signed-off-by: Jayapriya Pai janantha@redhat.com
**Description:**
Add alert rules for controller, create service and servicemonitor
> feat: add alert rules for mso

- deploy/operator/monitoring-stack-operator-deployment.yaml
jira: https://issues.redhat.com/browse/MON-2353
Signed-off-by: jooho <jlee@redhat.com>
> fix: Increase resource(memory) limit of mso operator

- hack/olm/subscription.yaml
> fix: subscription source should be observability-operator #156

- .github/workflows/pr-checks.yaml
- .gitignore
- Makefile
- bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
- bundle/manifests/monitoring.rhobs_thanosqueriers.yaml
- bundle/manifests/observability-operator-alertmanager-rules_monitoring.coreos.com_v1_prometheusrule.yaml
- bundle/manifests/observability-operator-prometheus-operator-rules_monitoring.coreos.com_v1_prometheusrule.yaml
- bundle/manifests/observability-operator-prometheus-rules_monitoring.coreos.com_v1_prometheusrule.yaml
- bundle/manifests/observability-operator-rules_monitoring.coreos.com_v1_prometheusrule.yaml
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- bundle/manifests/observability-operator_monitoring.coreos.com_v1_servicemonitor.yaml
- bundle/manifests/observability-operator_rbac.authorization.k8s.io_v1_rolebinding.yaml
- bundle/manifests/observability-operator_v1_service.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- deploy/olm/kustomization.yaml
Two changes to support internal build pipelines. This introduces no functional changes, only a new `build` target and the addition of OLM artifacts to the tracked files.
> Internal build changes

- Makefile
> build: add .PHONY: build

- deploy/olm/syncselector-template.yaml
First version based on an internal testing template and
https://github.com/openshift/addon-operator/blob/main/hack/olm-registry/olm-artifacts-template.yaml
> MON-2677: chore: add app-interface artifact

- pkg/controllers/monitoring/monitoring-stack/controller.go
* Needed this to help debug why my prometheus was not deployed
> Add logging for reconcile errors

- deploy/olm/syncselector-template.yaml
> fix: target management clusters in SSS

- README.md
> Updating Slack information in the README.

- bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
- deploy/operator/observability-operator-cluster-role.yaml
- deploy/samples/monitoring-stack.yaml
- deploy/samples/multi-ns-stack.yaml
- docs/api.md
- pkg/apis/monitoring/v1alpha1/types.go
- pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
- pkg/controllers/monitoring/monitoring-stack/alertmanager.go
- pkg/controllers/monitoring/monitoring-stack/components.go
- pkg/controllers/monitoring/monitoring-stack/controller.go
- test/e2e/monitoring_stack_controller_test.go
feat: add support for monitoring multiple namespaces
JIRA: https://issues.redhat.com/browse/MON-2846
> feat: add support for watching multiple namespaces

- Makefile
> build: tag catalog images with last main commit

- bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
- deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
- docs/api.md
- pkg/apis/monitoring/v1alpha1/types.go
fix description of `namespaceSelector` and `resourceSelector` to unify the empty and null
> improve namespace and resource selector docs

- Makefile
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- deploy/olm/kustomization.yaml
- deploy/package-operator/operator/kustomization.yaml
fix: updated Obo image version in CSV
fix: increase timeout for installing OLM on kind cluster
fixes: #273
> fix: updated Obo image version in CSV

- bundle/manifests/observability-operator.clusterserviceversion.yaml
- deploy/olm/bases/observability-operator.clusterserviceversion.yaml
> fix: update url link to rhobs-handbook.netlify.app

- .github/workflows/release.yaml
> ci: build test-harness for dev releases

- bundle/manifests/monitoring.rhobs_alertmanagerconfigs.yaml
- bundle/manifests/monitoring.rhobs_alertmanagers.yaml
- bundle/manifests/monitoring.rhobs_podmonitors.yaml
- bundle/manifests/monitoring.rhobs_probes.yaml
- bundle/manifests/monitoring.rhobs_prometheusagents.yaml
- bundle/manifests/monitoring.rhobs_prometheuses.yaml
- bundle/manifests/monitoring.rhobs_prometheusrules.yaml
- bundle/manifests/monitoring.rhobs_scrapeconfigs.yaml
- bundle/manifests/monitoring.rhobs_servicemonitors.yaml
- bundle/manifests/monitoring.rhobs_thanosrulers.yaml
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- deploy/dependencies/kustomization.yaml
After enable operator-sdk gzip compression here: https://github.com/rhobs/observability-operator/pull/361
stripped down crds hack is not needed anymore.
> fix: remove stripped down crds hack

- bundle/manifests/monitoring.rhobs_alertmanagerconfigs.yaml
- bundle/manifests/monitoring.rhobs_alertmanagers.yaml
- bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
- bundle/manifests/monitoring.rhobs_podmonitors.yaml
- bundle/manifests/monitoring.rhobs_probes.yaml
- bundle/manifests/monitoring.rhobs_prometheusagents.yaml
- bundle/manifests/monitoring.rhobs_prometheuses.yaml
- bundle/manifests/monitoring.rhobs_prometheusrules.yaml
- bundle/manifests/monitoring.rhobs_scrapeconfigs.yaml
- bundle/manifests/monitoring.rhobs_servicemonitors.yaml
- bundle/manifests/monitoring.rhobs_thanosrulers.yaml
- bundle/manifests/obo-prometheus-operator-admission-webhook_policy_v1_poddisruptionbudget.yaml
- bundle/manifests/obo-prometheus-operator-admission-webhook_v1_service.yaml
- bundle/manifests/obo-prometheus-operator_v1_service.yaml
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
- deploy/dependencies/kustomization.yaml
- docs/api.md
- go.mod
- go.sum
[MON-3408](https://issues.redhat.com/browse/MON-3408)
> feat: bump Prometheus operator to v0.69.0

- test/run-e2e-ocp.sh
Add timeout when check installation status of obo
Fix issue [COO-40](https://issues.redhat.com/browse/COO-40) error: timed out waiting for the condition on sub when install obo
> test: fix test script on ocp

- test/e2e/framework/assertions.go
fix issue https://issues.redhat.com/browse/COO-159
> fix: null pointer error of case NoOwnerRefInvalidNamespaceReasonEvent

- test/e2e/monitoring_stack_controller_test.go
https://issues.redhat.com/browse/COO-85
> test: enhance case to cover prometheus web ui

- bundle/manifests/monitoring.rhobs_alertmanagerconfigs.yaml
- bundle/manifests/monitoring.rhobs_alertmanagers.yaml
- bundle/manifests/monitoring.rhobs_podmonitors.yaml
- bundle/manifests/monitoring.rhobs_probes.yaml
- bundle/manifests/monitoring.rhobs_prometheusagents.yaml
- bundle/manifests/monitoring.rhobs_prometheuses.yaml
- bundle/manifests/monitoring.rhobs_prometheusrules.yaml
- bundle/manifests/monitoring.rhobs_scrapeconfigs.yaml
- bundle/manifests/monitoring.rhobs_servicemonitors.yaml
- bundle/manifests/monitoring.rhobs_thanosrulers.yaml
- bundle/manifests/obo-prometheus-operator-admission-webhook_policy_v1_poddisruptionbudget.yaml
- bundle/manifests/obo-prometheus-operator-admission-webhook_v1_service.yaml
- bundle/manifests/obo-prometheus-operator_v1_service.yaml
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- deploy/dependencies/kustomization.yaml
This syncs the version with the included go module.
> build: update prometheus-operator manifests to 0.75.2

- pkg/controllers/uiplugin/components.go
- pkg/controllers/uiplugin/config/korrel8r.yaml
- pkg/controllers/uiplugin/plugin_info_builder.go
- pkg/controllers/uiplugin/troubleshooting_panel.go
> feat: add Trace support in korrel8r

- bundle/manifests/observability-operator.clusterserviceversion.yaml
- deploy/olm/bases/observability-operator.clusterserviceversion.yaml
Closes [COO-474](https://issues.redhat.com//browse/COO-474)
> COO-474: fix: hide Prometheus operator CRDs in UI

- pkg/controllers/operator/controller.go
- pkg/operator/scheme.go
Instead of trying to shoehorn it into the controller.
Fixes: [COO-525](https://issues.redhat.com//browse/COO-525)
> operator: register scheme in operator

- bundle/manifests/monitoring.rhobs_alertmanagerconfigs.yaml
- bundle/manifests/monitoring.rhobs_alertmanagers.yaml
- bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
- bundle/manifests/monitoring.rhobs_podmonitors.yaml
- bundle/manifests/monitoring.rhobs_probes.yaml
- bundle/manifests/monitoring.rhobs_prometheusagents.yaml
- bundle/manifests/monitoring.rhobs_prometheuses.yaml
- bundle/manifests/monitoring.rhobs_prometheusrules.yaml
- bundle/manifests/monitoring.rhobs_scrapeconfigs.yaml
- bundle/manifests/monitoring.rhobs_servicemonitors.yaml
- bundle/manifests/monitoring.rhobs_thanosqueriers.yaml
- bundle/manifests/monitoring.rhobs_thanosrulers.yaml
- bundle/manifests/obo-prometheus-operator-admission-webhook_policy_v1_poddisruptionbudget.yaml
- bundle/manifests/obo-prometheus-operator-admission-webhook_v1_service.yaml
- bundle/manifests/obo-prometheus-operator_v1_service.yaml
- bundle/manifests/observability-operator.clusterserviceversion.yaml
- deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
- deploy/crds/common/monitoring.rhobs_thanosqueriers.yaml
- deploy/dependencies/kustomization.yaml
- pkg/apis/monitoring/v1alpha1/types.go
Fixes: [COO-666](https://issues.redhat.com//browse/COO-666)
> COO-666: Fix support annotation 1.0

- cmd/operator/main.go
- docs/user-guides/observability-ui-plugins.md
* Updated Health Analyzer to v0.4.0
* Updated docs with incidents config
[OBSINTA-235](https://issues.redhat.com//browse/OBSINTA-235)
> chore: update Health Analyzer release version

- test/run-e2e-ocp.sh
[COO-712](https://issues.redhat.com/browse/COO-712)
> fix: test script failure when enable OCP feature gate

- test/e2e/monitoring_stack_controller_test.go
web UI url changed in downstream
[COO-775](https://issues.redhat.com/browse/COO-775)
> fix: web UI case failure in downstream

- test/e2e/monitoring_stack_controller_test.go
web UI url changed in downstream
> fix: web UI case failure in downstream (#719)

- docs/user-guides/observability-ui-plugins.md
Jira: [OU-832](https://issues.redhat.com//browse/OU-832) - [obo] Create documentation for Perses RBAC
> docs: perses rbac documentation under monitoring section

- pkg/controllers/uiplugin/components.go
- pkg/controllers/uiplugin/health_analyzer.go
This reverts commit 315b43660968fe0e4a8e66e33a1fc4eb4643f9ea, but keep the original image version,
> fix: reverting - add cluster-health-analyzer v0.5.1 (#785)

- deploy/crds/common/kustomization.yaml
- deploy/crds/kubernetes/kustomization.yaml
- deploy/dependencies/kustomization.yaml
- deploy/package-operator/crds/kustomization.yaml
- deploy/package-operator/dependencies-kubeconfig/kustomization.yaml
- deploy/package-operator/dependencies/kustomization.yaml
- deploy/perses/crds/kustomization.yaml
- deploy/samples/kustomization.yaml
- deploy/scorecard/kustomization.yaml
> chore: kustomize edit fix on all kustomization.yaml

- pkg/controllers/observability/tempo_components.go
https://issues.redhat.com/browse/COO-1262
> fix: observabilityinstaller fix AWS STS config
